name: Trigger Semgrep Scan 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-semgrep-scan:
    name: Run Semgrep Scan 
    uses: ramesherrorhunter/semgrep/.github/workflows/semgrep.yml@main
    secrets:
        SEMGREP_API_TOKEN: ${{ secrets.SEMGREP_API_TOKEN }}
